### ISSUE TITLE
Jitsi Meeting, 5 June 2021, 2pm UTC

### ISSUE THREAD

**Issue by enockseth** [LinuxAccra-UserGroup/meetings#1]
- Date: 5 June 2021
- Time: Linux Accra time [14:00 UTC +0](https://www.timeanddate.de/zeitzonen/events?msg=Linux+Accra+Meetup&iso=20210605T14)
- Venue: https://meet.ffmuc.net/LinuxAccraUserGroup

# Agenda
- _Kindly comment agenda recommendations or what you would like to share_

**Comment by e-Fafali** [comment]
Can we talk about the open-source hardware movement?

**Comment by enockseth** [comment]
Sure, let's chat about it together and schedule some upcoming sessions :)
