### ISSUE TITLE
Introduction to video recording and live streaming with OBS Studio

### ISSUE THREAD

**Issue by enockseth** [LinuxAccra-UserGroup/meetings#6]
- Date: 30 November 2024 
- Venue: AITI-KACE, Accra and Online: https://osmvideo.cloud68.co/user/eno-o9p-4zc-olg
- Time: 14:00 - 17:00 UTC

## Outline
- Introduction
- Scenes & Sources
- Recording
- Streaming, RTMP
- Profiles
- [FFmpeg](https://en.wikipedia.org/wiki/FFmpeg)
- Etc...

## Resources
- https://obsproject.com/
- https://c3voc.de/wiki/distributed-conference
- https://github.com/tiangolo/nginx-rtmp-docker

**Comment by laudb** [comment]
Tentative setup for Linux Accra meeting at GI-KACE
1) Laptop with linux OS and OBS
2) Projector
3) Webcam
4) Microphone
5) Speaker
6) Internet (Local wifi, AT router as backup)

**Comment by enockseth** [comment]
The session took place with 4 participants, three in-person and one remote.
It ended with chit-chat and news from members.
